apiVersion: apps/v1
kind: Deployment
metadata:
    name: vote
spec:
    replicas: 1
    selector:
        matchLabels:
          app: vote
    template:
        metadata:
          name: vote
          labels:
            app: vote
        spec:
          containers:
            - name: vote
              image: dipesh017/demo:vote
              resources:
                requests:
                    cpu: "1"
                    memory: "1Gi"
                limits:
                    cpu: "2"
                    memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote
