apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-c42-tbd
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 20
  - name: ng-2
    minsize: 2
    maxsize: 2
    instancesDistribution:
        maxPrice: 0.05
        instanceTypes: ["t3.small", "t2.small"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: "capacity-optimized"
availabilityZones: ['us-east-1a', 'us-east-1b']
