apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-c42-tbd
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 20
availabilityZones: ['us-east-1a', 'us-east-1b']
