apiVersion: apps/v1
kind: Deployment
metadata:
    name: vote
spec:
    replicas: 4
    selector:
        matchLabels:
          app: vote
    template:
        metadata:
          name: vote
          labels:
            app: vote
        spec:
          containers:
            - name: vote
              image: dipesh017/demo:vote

---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: vote
