apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            batch: c42
    template:
        metadata:
          name: nginx
          labels:
            batch: c42
        spec:
          containers:
            - name: nginx
              image: nginx
